### ISSUE TITLE
Restaurant Search

### ISSUE THREAD

**Issue by ryan-mapa** [ryan-mapa/tableup#6]

**Comment by ryan-mapa** [comment]
Add Core Feature Label

**Comment by ryan-mapa** [comment]
Pretty basic search ready for a look. Considering potentially adding a filter by city if there's time.

**Comment by rkoeze** [comment]
Looks solid. Please add some sort of message when no restaurants returned, e.g. `No Restaurants Found`, so users know they didn't hit a bug.
